const API_BASE_URL = "https://localhost:7190/api/";

const ENDPOINTS = {
    GET_BOOK: "Book/",
    GET_MULTIPLE_BOOKS: "Book/Multiple/",
    GET_BOOK_IMAGE: "Image/Book/",
    GET_CRITERIA: "Criteria",
    LOGIN: "Account/Login",
    ORDER: "Order",
    GET_GENDERS: "Gender",
    GET_ID_TYPES: "Identification"
};


const development = {
    API_URL_GET_BOOK: `${API_BASE_URL}${ENDPOINTS.GET_BOOK}`,
    API_URL_GET_MULTIPLE_BOOKS: `${API_BASE_URL}${ENDPOINTS.GET_MULTIPLE_BOOKS}`,
    API_URL_GET_BOOK_IMAGE: `${API_BASE_URL}${ENDPOINTS.GET_BOOK_IMAGE}`,
    API_URL_GET_CRITERIA: `${API_BASE_URL}${ENDPOINTS.GET_CRITERIA}`,
    API_URL_LOGIN: `${API_BASE_URL}${ENDPOINTS.LOGIN}`,
    API_URL_ORDER: `${API_BASE_URL}${ENDPOINTS.ORDER}`,
    API_URL_GET_GENDERS: `${API_BASE_URL}${ENDPOINTS.GET_GENDERS}`,
    API_URL_GET_ID_TYPES: `${API_BASE_URL}${ENDPOINTS.GET_ID_TYPES}`
};

const API = development;
export default API;